---
- name: Google repo signing key
  ansible.builtin.get_url:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    dest: /etc/apt/trusted.gpg.d/google.asc
    mode: '0644'
    force: true

- name: Chrome repository source
  ansible.builtin.deb822_repository:
    name: google-chrome
    types: deb
    uris: http://dl.google.com/linux/chrome/deb/
    suites: stable
    components: main
    signed_by: /etc/apt/trusted.gpg.d/google-chrome.gpg

- name: Google Chrome stable package
  ansible.builtin.package:
    name: google-chrome-stable
    update_cache: true
    state: present
