---
# Of course, Docker Desktop is not in the Docker repo
# FIXME: remove this and just import the key instead
- name: Docker general repository source
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present
  when:
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "13"

# Docker Desktop documentation indicates this requirement
- name: Docker desktop requirement (gnome-terminal) for XFCE
  ansible.builtin.package:
    name: gnome-terminal
    update_cache: true
    state: present
  when:
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "13"

- name: Install Docker Desktop from remote .deb file
  ansible.builtin.apt:
    deb: https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb
    state: present
    update_cache: true
  when:
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "13"
