- name: Desktop packages
  ansible.builtin.package:
    name: "{{ desktop_packages }}"
    update_cache: yes
    state: latest

- name: Desktop packages for development
  ansible.builtin.package:
    name: "{{ desktop_dev_packages }}"
    state: present
  when: include_desktop_dev_packages

- name: Google Chrome
  include_tasks: chrome.yml
  when: include_chrome

- name: VSCodium
  include_tasks: vscodium.yml
  when: include_desktop_dev_packages

- name: KVM packages
  ansible.builtin.package:
    name:
      - qemu-system
      - libvirt-daemon-system
    state: present
  when:
    - hypervisor == "kvm"

- name: Add user "{{ dev_user }}" to libvirt group
  user:
    name: "{{ dev_user }}"
    groups: libvirt
    append: true
  when:
    - hypervisor == "kvm"
    - dev_user is defined

- name: VirtualBox repository source
  ansible.builtin.deb822_repository:
    name: virtualbox
    types: deb
    uris: http://download.virtualbox.org/virtualbox/debian
    suites: "{{ ansible_distribution_release }}"
    components: contrib
    signed_by: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when:
    - hypervisor == "virtualbox"
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "12"

- name: VirtualBox package
  ansible.builtin.package:
    name: "{{ virtualbox_package_name }}"
    update_cache: yes
    state: latest
  when:
    - hypervisor == "virtualbox"
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "12"
