---
# FIXME: split into development desktop role

- name: Desktop packages
  ansible.builtin.package:
    name: "{{ desktop_packages }}"
    update_cache: true
    state: present

- name: Desktop packages for development
  ansible.builtin.package:
    name: "{{ desktop_dev_packages }}"
    state: present
  when: include_desktop_dev_packages | bool

- name: Google Chrome
  ansible.builtin.include_tasks: chrome.yml
  when: include_chrome | bool

- name: VSCodium
  ansible.builtin.include_tasks: vscodium.yml
  when:
    - include_desktop_dev_packages | bool
    - include_vscodium | bool

- name: KVM packages
  ansible.builtin.package:
    name:
      - qemu-system
      - libvirt-daemon-system
    state: present
  when:
    - hypervisor == "kvm"

- name: Add user to libvirt group ({{ dev_user }})
  ansible.builtin.user:
    name: "{{ dev_user }}"
    groups: libvirt
    append: true
  when:
    - hypervisor == "kvm"
    - dev_user is defined

- name: VirtualBox repository source
  ansible.builtin.deb822_repository:
    name: virtualbox
    types: deb
    uris: http://download.virtualbox.org/virtualbox/debian
    suites: "{{ ansible_distribution_release }}"
    components: contrib
    signed_by: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when:
    - hypervisor == "virtualbox"
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "12"

- name: VirtualBox package
  ansible.builtin.package:
    name: "{{ virtualbox_package_name }}"
    update_cache: true
    state: present
  when:
    - hypervisor == "virtualbox"
    - ansible_distribution | lower == "debian"
    - ansible_distribution_major_version == "12"

- name: Docker Desktop
  ansible.builtin.include_tasks: docker_desktop.yml

- name: Vagrant
  ansible.builtin.include_tasks: vagrant.yml
