---
- hosts: nas
  become: true

  tasks:
  - name: Security
    include_role:
      name: security
  - name: Base
    include_role:
      name: base
  - name: Data
    include_role:
      name: data
  - name: Nginx
    include_role:
      name: geerlingguy.nginx
