---
- name: Prepare user output
  set_fact:
    output_user_name: "{{ user_name }}"

- name: User group for "{{ output_user_name }}"
  group:
    name: "{{ user_name }}"

- name: User "{{ output_user_name }}"
  user:
    name: "{{ user_name }}"
    uid: "{{ user_uid | default(omit) }}"
    group: "{{ user_name }}"
    shell: "{{ user_shell_path | default(omit) }}"

- name: User .ssh directory for "{{ output_user_name }}"
  file:
    path: "/home/{{ user_name }}/.ssh/"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'

- name: User authorized SSH public keys for "{{ output_user_name }}"
  template:
    src: authorized_keys.j2
    dest: "/home/{{ user_name }}/.ssh/authorized_keys"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0400'

- name: Passwordless sudoers for "{{ output_user_name }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ user_name }}'
    line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  when:
    - user_nopass_sudo is defined
    - user_nopass_sudo | bool
